<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Title>IVSoftware.Portable.Reconciler</Title>
		<Description>Comparer analyzes Only-In and Newer-In items for two collections.</Description>
		<PackageTags>collections;icomparable;versioning;synchronize;reconcile;portable;net;android;ios</PackageTags>
		<PackageProjectUrl>https://github.com/IVSoftware/IVSoftware.Portable.Reconciler.git</PackageProjectUrl>
		<RepositoryUrl>https://github.com/IVSoftware/IVSoftware.Portable.Reconciler.git</RepositoryUrl>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Authors>IVSoftware, Thomas C. Gregor</Authors>
		<Owner>IVSoftware LLC</Owner>
		<Copyright>Copyright © 2023 IVSoftware LLC</Copyright>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>
			- Updated ReadMe with additional documentation on the [Equals] tuple.
			- To provide more accurate search results on the listing, a duplicate PackageTags entry has been identified and removed.
			- These are cosmetic improvements that do not alter the functionality.
		</PackageReleaseNotes>
		<DebugType>embedded</DebugType>
		<BaseVersion>1.0.3</BaseVersion>
		<VersionPrefix>$(BaseVersion)</VersionPrefix>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<SignAssembly>False</SignAssembly>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>231130.ivs.pfx</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="IVSoftware.Portable.Disposable" Version="1.2.0" />
	</ItemGroup>
</Project>


